### ISSUE TITLE
Architecture Question -- TimeSeries Data transfer class

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/ExcelToCWMS#1]
There is a class  Hec.cwms.TimeSeries.    It may need to be in a separate assembly?   The class is used to return data from a database.

We plan to use the same class to return TimeSeries data from Excel, so it doesn't feel right that you need to include CWMS when working with Excel. 

For the small project it may not matter, but I'm looking to learn more about decoupling.

**Comment by HenryGeorgist** [comment]
I am not sure what you are really asking. One way I tend to decouple is to design to an interface rather than a class. Are you working cross language here? It seems there is C# code, but are you referencing java objects?

**Comment by ktarbet** [comment]
Just C#.

**Comment by HenryGeorgist** [comment]
I would create a package or a library that contains my interfaces. ITimeSeries might be one interface I would create. Another might be IProvideTimeSeries which has a method to return a time series for a given query. Does that make sense? The interface, and likely the concrete instance are probably not appropriately stored in the HEC.CWMS path, it might  be more like HEC.DATA because it is an agnostic data container, non specific to any time of data provider.

**Comment by ktarbet** [comment]
Yes that makes sense.  If we create another project/assembly we could move the concrete TimeSeries into that assembly.  Would the interface have any advantage at that point.

**Comment by HenryGeorgist** [comment]
I tend to err on the side of making everything an interface and referring to the interface rather than a concrete class. It helps me to understand that the interface defines how my program communicates. It requires me to be very careful about thinking through what something is and what it does rather than just adding methods or properties to a class because the need arises somewhere. It forces structured communication.
